const {test,before,after}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'hunger-test-'));
process.env.DB_FILE=path.join(dir,'game.db');process.env.JWT_SECRET='regression-only-secret';delete process.env.OPENAI_API_KEY;
const {app,ready}=require('../server');const {db}=require('../database');let server,base,alice,bob,id;
async function request(route,body,token,method=body===undefined?'GET':'POST'){const r=await fetch(base+route,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:r.headers.get('content-type')?.includes('json')?await r.json():await r.text()};}
before(async()=>{await ready;server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base='http://127.0.0.1:'+server.address().port;alice=(await request('/api/register',{username:'alice',password:'test-password'})).data.token;bob=(await request('/api/register',{username:'bob',password:'test-password'})).data.token;id=(await request('/api/saves',{saveName:'Round',storyState:'{"inkSaveVersion":10}',characterData:{health:0}},alice)).data.save.id;});
after(async()=>{await new Promise(r=>server.close(r));await new Promise(r=>db.close(r));fs.rmSync(dir,{recursive:true,force:true});});
test('read, update, delete and stats cannot access another account save',async()=>{assert.equal((await request('/api/saves/'+id,undefined,bob)).status,404);assert.equal((await request('/api/saves/'+id,{storyState:'{}',characterData:{}},bob,'PUT')).status,404);assert.equal((await request('/api/saves/'+id,undefined,bob,'DELETE')).status,404);assert.equal((await request('/api/stats',{saveId:id,stats:{actionsPerformed:1}},bob)).status,404);assert.equal((await request('/api/saves/'+id,undefined,alice)).data.save.character_data.health,0);});
test('statistics upsert one record and reject invalid values',async()=>{for(const n of [2,3])assert.equal((await request('/api/stats',{saveId:id,stats:{actionsPerformed:n}},alice)).status,200);const rows=(await request('/api/stats',undefined,alice)).data.stats;assert.equal(rows.length,1);assert.equal(rows[0].actions_performed,3);assert.equal((await request('/api/stats',{saveId:id,stats:{actionsPerformed:-1}},alice)).status,400);});
test('public password reset routes and feedback listing are unavailable',async()=>{for(const route of ['/api/admin/reset-password','/api/admin/reset-dev'])assert.equal((await request(route,{username:'alice',newPassword:'hacked'})).status,404);assert.equal((await request('/api/feedback')).status,404);});
test('malformed input returns client errors; fallback actions work without AI key',async()=>{assert.equal((await request('/api/register',{username:[],password:{}})).status,400);assert.equal((await request('/api/free-roam',{})).status,400);assert.equal((await request('/api/free-roam',{action:'wait',playerStats:{health:0}})).status,200);assert.equal((await request('/api/saves',{saveName:'bad',storyState:[],characterData:{}},alice)).status,400);});
test('leaderboard binds username to authenticated account',async()=>{assert.equal((await request('/api/leaderboard',{username:'fake',district:'1',winType:'Hunger Games Champion'})).status,401);assert.equal((await request('/api/leaderboard',{username:'fake',district:'1',winType:'Cheat Win'},alice)).status,200);assert.equal((await request('/api/leaderboard')).data.leaderboard[0].username,'alice');});
test('deleting an owned save also removes associated statistics',async()=>{assert.equal((await request('/api/saves/'+id,undefined,alice,'DELETE')).status,200);assert.equal((await request('/api/stats',undefined,alice)).data.stats.length,0);});
