const {test,before,after}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'director-api-'));process.env.DB_FILE=path.join(dir,'game.db');process.env.JWT_SECRET='director-test-only';process.env.OPENAI_API_KEY='provider-test-only';
const realFetch=global.fetch;let providerCalls=0,fail=false;
global.fetch=async(url,options)=>{if(String(url).startsWith('https://api.openai.com/')){providerCalls++;if(fail)throw Error('Test provider offline');const body=JSON.parse(options.body);const result=body.response_format.json_schema.schema.properties.narrative?{narrative:'The clearing is still as you weigh the paths ahead.'}:{action:'north'};return {ok:true,json:async()=>({choices:[{message:{content:JSON.stringify(result)}}]})};}return realFetch(url,options);};
const {app,ready}=require('../server');const {db}=require('../database');const engine=require('../public/survival');let server,base,token;
async function request(route,body,auth){const r=await realFetch(base+route,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(auth?{Authorization:'Bearer '+auth}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()};}
before(async()=>{await ready;server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base='http://127.0.0.1:'+server.address().port;token=(await request('/api/register',{username:'director-player',password:'test-password'})).data.token;});
after(async()=>{await new Promise(r=>server.close(r));db.close();global.fetch=realFetch;fs.rmSync(dir,{recursive:true,force:true});});
test('paid narration requires authentication while local narration remains available',async()=>{const state=engine.create({seed:1});assert.equal((await request('/api/ai/status')).data.available,true);assert.equal((await request('/api/free-roam',{action:'search',state,mode:'ai'})).status,401);assert.equal(providerCalls,0);assert.equal((await request('/api/free-roam',{action:'search',state,mode:'local'})).data.source,'local');assert.equal(providerCalls,0);});
test('authenticated narration and constrained intent use the provider successfully',async()=>{const state=engine.create({seed:1}),before=JSON.stringify(state);const narration=await request('/api/free-roam',{action:'search',state,events:['You found wood.'],mode:'ai'},token);assert.equal(narration.status,200);assert.equal(narration.data.source,'ai');const intent=await request('/api/ai/intent',{action:'take the northern trail silently',state,mode:'ai'},token);assert.equal(intent.data.action,'north');assert.equal(intent.data.source,'ai');assert.equal(JSON.stringify(state),before);});
test('provider outages return a usable local narration without a server error',async()=>{fail=true;const result=await request('/api/free-roam',{action:'rest',state:engine.create({seed:1}),mode:'ai'},token);assert.equal(result.status,200);assert.equal(result.data.source,'local');assert.equal(result.data.reason,'provider_unavailable');assert.ok(result.data.response);});
